name: CICD - MAIN
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
jobs:
  Build:
    uses: Harshal-HP/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: 'nodeJS'
      appName: 'user'
    secrets:
      vault_token: ${{ secrets.vault_token }}